### ISSUE TITLE
eventsourcing should be a left fold

### ISSUE THREAD

**Issue by reharik** [assafg/osiris#3]
Hi, this is an interesting library, and I applaud anyone who works to bring ES to the publics eyes.
real quick silly little typeo if you search your read me for waht you'll find one.
But more interestingly, in the read me the way you describe the ES process it looks like basically the last event that lands is the current state. If this is the case then there in no need to retrieve all the events except to re run projections.  In ES the current state is a left fold or map reduce of all the events in the entities life type ( or at least since last snapshot.  Perhaps you have it this way for simplicity sake, I understand that the notion of doing a fold over all the events of entity is scary to people, for some reason, and raises the barrier to entry.  Perhaps if you linked to some good ES literature in your read me you could put the wight of selling ES on the literature and just say "if you want to do it here's how if you want a great tool here one is.
Just some thoughts.  Great work. Great name too.  I have a dependency injection framework called dagon ( a Babylonian god, but the pun is on dag (directed acyclic graph) ) but osiris is a much better name. :)

**Comment by assafg** [comment]
Thanks for your comment. I appreciate it. 
In basic cases you are correct - the last event is basically the state and there is no need to "dig deeper". I avoid relying on this logic as I strive to keep this lib as generic as possible. As you can see in the code and I try to demonstrate in the examples - I use 'reduce' to get the state since the last snapshot.
I will link to external literature as per your advise.

Thanks again!
